<?php

    namespace app\modules\admin\models;

    use Yii;
    use yii\web\UploadedFile;

    /**
     * This is the model class for table "banner".
     *
     * @property int $id
     * @property string|null $image
     */
    class Banner extends \yii\db\ActiveRecord
    {
        public $file;

        /**
         * {@inheritdoc}
         */
        public static function tableName()
        {
            return 'banner';
        }

        /**
         * {@inheritdoc}
         */
        public function rules()
        {
            return [
                [['image'], 'string', 'max' => 255],
                [['image'], 'default', 'value' => 'images/default/no-image.png'],
                [['file'], 'image'],
            ];
        }

        /**
         * {@inheritdoc}
         */
        public function attributeLabels()
        {
            return [
                'id'    => 'ID',
                'image' => 'Картинка по умолчанию',
                'file'  => 'Картинка по умолчанию ',
            ];
        }

        public function beforeSave($insert)
        {
            $arr = [
                'image' => 'file',
            ];

            foreach ( $arr as $item => $value ) {
                if ( $file = UploadedFile::getInstance($this, $value) ) {

                    $dir = 'images/banner/' . date("Y-m-d") . '/';
                    if ( !is_dir($dir) ) {
                        mkdir($dir);
                    }

                    $file_name = uniqid() . '_' . $file->baseName . '.' . $file->extension;
                    $this->$item = $dir . $file_name;
                    $file->saveAs($this->$item);
                }
            }

            return parent::beforeSave($insert); // TODO: Change the autogenerated stub
        }
    }
