<?php


    namespace app\controllers;


    use app\models\ContactForm;
    use app\models\Menu;
    use Yii;
    use yii\helpers\Html;
    use yii\web\Controller;

    class AppController extends Controller
    {

        public function beforeAction($action)
        {
            $this->view->title = \Yii::$app->name;

            $this->view->params['menu'] = Menu::find()->orderBy(['id' => SORT_DESC])->all();


            return parent::beforeAction($action); // TODO: Change the autogenerated stub
        }

        protected function setMeta($title = null, $keywords = null, $description = null)
        {
            $this->view->title = $title;
            $this->view->registerMetaTag(['name' => 'keywords', 'content' => "$keywords"]);
            $this->view->registerMetaTag(['name' => 'description', 'content' => "$description"]);
        }



    }